### ISSUE TITLE
relate field xx_id  can''t auto creat

### ISSUE THREAD

**Issue by bsbrother** [lsbardel/python-stdnet#57]
I like this soft , think again to the author , now i meet simple error:

from stdnet import odm

class Instrument(odm.StdModel):
    name = odm.SymbolField(unique=True)

class Position(odm.StdModel):
    instrument = odm.ForeignKey(Instrument)
    size = odm.FloatField()

odm.register(Instrument, 'redis://127.0.0.1:6379?db=0')
odm.register(Position, 'redis://127.0.0.1:6379?db=0')

i1 = Instrument(name='i1').save()
p1 = Position(size=1.0).save()

---

```
p1 = Position(size=1.0).save() 
```

......
  File "/home/luyserver/go/sites/python-stdnet/stdnet/backends/redisb.py", line 866, in execute_session
    json.dumps(instance._dbdata['errors']))
stdnet.exceptions.FieldValueError: {"instrument_id": "Field 'instrument_id' is required for '__main__.position'."}

why relate field instrument_id  can''t auto creat?

think you very much!

**Comment by lsbardel** [comment]
Because it doesn't know how to do that. Instrument in your model is a `ForeignKey`, `Position` doesn't know how to create a instance of `Instrument`. In your example you should do:

```
i1 = Instrument(name='i1').save()
p1 = Position(size=1.0, instrument=i1).save()
```

Alternatively you can:
- set the `default` attribute to a factory of `Instrument`:
  
  ```
  def create_random_instrument():
       return Instrument(name='random').save()
  
  class Position(odm.StdModel):
       instrument = odm.ForeignKey(Instrument, default=create_random_instrument)
       size = odm.FloatField()
  ```
  
  http://lsbardel.github.io/python-stdnet/api/fields.html#stdnet.odm.Field.default
- set the `required` attribute to `False`:
  
  ```
   class Position(odm.StdModel):
       instrument = odm.ForeignKey(Instrument, required=False)
       size = odm.FloatField()
  ```
  
  http://lsbardel.github.io/python-stdnet/api/fields.html#stdnet.odm.Field.required

Closing this
